services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mongo-data:/data/db # Agregado para persistencia de datos

  mongoclient:
    image: alpine/mongosh
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo-network
    command: ["tail", "-f", "/dev/null"]
    restart: always

  calculadora:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://admin_user:web3@mongo:27017/?authSource=admin
    ports:
      - "8089:8000"
    networks:
      - mongo-network
    volumes:
      - ./backend:/app
    restart: always
    depends_on:
      mongo:
        condition: service_healthy

  # --- NUEVO SERVICIO DE FRONTEND ---
  frontend:
    build:
      context: ./frontend # Apunta a la carpeta de tu app React
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapea el puerto de React al host
    volumes:
      - ./frontend:/app # Monta el c√≥digo para live-reloading
      - /app/node_modules # Evita que la carpeta node_modules local sobreescriba la del contenedor
    networks:
      - mongo-network # Para que pueda comunicarse con el backend
    depends_on:
      - calculadora # Opcional, pero asegura que el backend inicie primero
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true # Necesario para que el hot-reloading funcione bien en Docker

networks:
  mongo-network:
    driver: bridge

volumes: # Agregado para la persistencia de la base de datos
  mongo-data: