global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["calculadora:8000"]

  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

